runtime: nodejs12
handlers:
  # Serve all static files with url ending with a file extension
  # - url: /service-worker.js
  #   static_files: build/service-worker.js
  #   upload: build/service-worker\.js
  #   expiration: 0m
  #   mime_type: application/javascript
  # - url: /
  #   static_files: build/index.html
  #   upload: build/index.html
  # - url: /(.*)$
  #   static_files: build/\1
  #   upload: build/(.*)
